FROM adoptopenjdk:11-jre-hotspot

WORKDIR /usr/src

COPY ./token-service/target/token-service-1.0.0-runner.jar /usr/src

# COPY ./token-service/target/lib /usr/src/lib

EXPOSE 8081

CMD java -Xmx64m \
      -jar token-service-1.0.0-runner.jar