# Author: Daniel (s151641)
# Author: Troels (s161791)

FROM adoptopenjdk:11-jre-hotspot

WORKDIR /usr/src

COPY ./rest/target/rest-1.0.0-runner.jar /usr/src

COPY ./rest/target/lib /usr/src/lib

EXPOSE 8080

CMD java -Xmx64m \
      -jar rest-1.0.0-runner.jar > rest-log.txt