FROM adoptopenjdk:11-jre-hotspot

WORKDIR /usr/src

COPY ./payment-service/target/payment-service-1.0.0-runner.jar /usr/src

COPY ./payment-service/target/lib /usr/src/lib

EXPOSE 8080

CMD java -Xmx64m \
      -jar payment-service-1.0.0-runner.jar